import { Injectable } from '@angular/core';
import { Country } from '../classes/country';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import CountryList from 'country-list-with-dial-code-and-flag';

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  private countries: Country[];

  constructor() {
      this.countries = this.countriesList.map(country => ({
          name: country.name,
          dialCode: "+"+country.dialCode,
          flag: country.flag,
          image: `https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/${country.code}.svg`,
          dialCodeLength:country.dialCodeLength
      }));
  }

  public getAllCountries(): Country[] {
      return this.countries;
  }

  countriesList:any[]=[
    { flag: 'AD', name: 'Andorra', dialCode: '376', dialCodeLength: 6},
    { flag: 'AE', name: 'United Arab Emirates', dialCode: '971', dialCodeLength: 9},
    { flag: 'AF', name: 'Afghanistan', dialCode: '93', dialCodeLength: 9},
    { flag: 'AG', name: 'Antigua and Barbuda', dialCode: '1-268', dialCodeLength: 10},
    { flag: 'AI', name: 'Anguilla', dialCode: '1-264', dialCodeLength: 10},
    { flag: 'AL', name: 'Albania', dialCode: '355', dialCodeLength: 9},
    { flag: 'AM', name: 'Armenia', dialCode: '374', dialCodeLength: 6},
    { flag: 'AO', name: 'Angola', dialCode: '244', dialCodeLength: 9},
    { flag: 'AQ', name: 'Antarctica', dialCode: '672', dialCodeLength: 6},
    { flag: 'AR', name: 'Argentina', dialCode: '54', dialCodeLength: [6,7,8]},					
    { flag: 'AS', name: 'American Samoa', dialCode: '1-684', dialCodeLength: 10},
    { flag: 'AT', name: 'Austria', dialCode: '43', dialCodeLength: [10,11]},			
    { flag: 'AU', name: 'Australia', dialCode: '61', suggested: true, dialCodeLength: 9},
    { flag: 'AW', name: 'Aruba', dialCode: '297', dialCodeLength: 7},
    { flag: 'AX', name: 'Alland Islands', dialCode: '358', min: 7, max: 10},				
    { flag: 'AZ', name: 'Azerbaijan', dialCode: '994', dialCodeLength: 9},
    { flag: 'BA', name: 'Bosnia and Herzegovina', dialCode: '387', dialCodeLength: 8},
    { flag: 'BB', name: 'Barbados', dialCode: '1-246', dialCodeLength: 10},
    { flag: 'BD', name: 'Bangladesh', dialCode: '880', dialCodeLength: 10},
    { flag: 'BE', name: 'Belgium', dialCode: '32', dialCodeLength: 9},
    { flag: 'BF', name: 'Burkina Faso', dialCode: '226', dialCodeLength: 8},
    { flag: 'BG', name: 'Bulgaria', dialCode: '359', dialCodeLength: 9},
    { flag: 'BH', name: 'Bahrain', dialCode: '973', dialCodeLength: 8},
    { flag: 'BI', name: 'Burundi', dialCode: '257', dialCodeLength: 8},
    { flag: 'BJ', name: 'Benin', dialCode: '229', dialCodeLength: 8},
    { flag: 'BL', name: 'Saint Barthelemy', dialCode: '590', dialCodeLength: 9},				
    { flag: 'BM', name: 'Bermuda', dialCode: '1-441', dialCodeLength: 10},
    { flag: 'BN', name: 'Brunei Darussalam', dialCode: '673', dialCodeLength: 7},
    { flag: 'BO', name: 'Bolivia', dialCode: '591', dialCodeLength: 9},
    { flag: 'BR', name: 'Brazil', dialCode: '55', dialCodeLength: 11},
    { flag: 'BS', name: 'Bahamas', dialCode: '1-242', dialCodeLength: 10},
    { flag: 'BT', name: 'Bhutan', dialCode: '975', dialCodeLength: 7},
    { flag: 'BV', name: 'Bouvet Island', dialCode: '47',dialCodeLength: 10 },			
    { flag: 'BW', name: 'Botswana', dialCode: '267', dialCodeLength: 7},
    { flag: 'BY', name: 'Belarus', dialCode: '375', dialCodeLength: 9},
    { flag: 'BZ', name: 'Belize', dialCode: '501', dialCodeLength: 7},
    { flag: 'CA', name: 'Canada', dialCode: '1', suggested: true, dialCodeLength: 10},
    { flag: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '61', dialCodeLength: 10},			
    { flag: 'CD', name: 'Congo, Democratic Republic of the', dialCode: '243', dialCodeLength: 7},	
    { flag: 'CF', name: 'Central African Republic', dialCode: '236', dialCodeLength: 8},
    { flag: 'CG', name: 'Congo, Republic of the', dialCode: '242', dialCodeLength: 9},	
    { flag: 'CH', name: 'Switzerland', dialCode: '41', dialCodeLength: 9},
    { flag: 'CI', name: "Cote d'Ivoire", dialCode: '225', dialCodeLength: 8},
    { flag: 'CK', name: 'Cook Islands', dialCode: '682', dialCodeLength: 5},
    { flag: 'CL', name: 'Chile', dialCode: '56', dialCodeLength: 9},
    { flag: 'CM', name: 'Cameroon', dialCode: '237', dialCodeLength: 9},
    { flag: 'CN', name: 'China', dialCode: '86', dialCodeLength: 11},
    { flag: 'CO', name: 'Colombia', dialCode: '57', dialCodeLength: 10},
    { flag: 'CR', name: 'Costa Rica', dialCode: '506', dialCodeLength: 8},
    { flag: 'CU', name: 'Cuba', dialCode: '53', dialCodeLength: 8},
    { flag: 'CV', name: 'Cape Verde', dialCode: '238', dialCodeLength: 7},
    { flag: 'CW', name: 'Curacao', dialCode: '599', dialCodeLength: 7},
    { flag: 'CX', name: 'Christmas Island', dialCode: '61', dialCodeLength: 9},	
    { flag: 'CY', name: 'Cyprus', dialCode: '357', dialCodeLength: 8},
    { flag: 'CZ', name: 'Czech Republic', dialCode: '420', dialCodeLength: 9},
    { flag: 'DE', name: 'Germany', dialCode: '49', suggested: true, dialCodeLength: 10},
    { flag: 'DJ', name: 'Djibouti', dialCode: '253', dialCodeLength: 10},
    { flag: 'DK', name: 'Denmark', dialCode: '45', dialCodeLength: 8},
    { flag: 'DM', name: 'Dominica', dialCode: '1-767', dialCodeLength: 10},
    { flag: 'DO', name: 'Dominican Republic', dialCode: '1-809', dialCodeLength: 10},
    { flag: 'DZ', name: 'Algeria', dialCode: '213', dialCodeLength: 9},
    { flag: 'EC', name: 'Ecuador', dialCode: '593', dialCodeLength: 9},
    { flag: 'EE', name: 'Estonia', dialCode: '372', dialCodeLength: 8},
    { flag: 'EG', name: 'Egypt', dialCode: '20', dialCodeLength: 10},
    { flag: 'EH', name: 'Western Sahara', dialCode: '212', dialCodeLength: 9},
    { flag: 'ER', name: 'Eritrea', dialCode: '291', dialCodeLength: 7},	
    { flag: 'ES', name: 'Spain', dialCode: '34', dialCodeLength: 9},
    { flag: 'ET', name: 'Ethiopia', dialCode: '251', dialCodeLength: 9},
    { flag: 'FI', name: 'Finland', dialCode: '358', min: 9, max: 11},
    { flag: 'FJ', name: 'Fiji', dialCode: '679', dialCodeLength: 7},
    { flag: 'FK', name: 'Falkland Islands (Malvinas)', dialCode: '500', dialCodeLength: 5},
    { flag: 'FM', name: 'Micronesia, Federated States of', dialCode: '691', dialCodeLength: 7},
    { flag: 'FO', name: 'Faroe Islands', dialCode: '298', dialCodeLength: 5},
    { flag: 'FR', name: 'France', dialCode: '33', suggested: true, dialCodeLength: 9},
    { flag: 'GA', name: 'Gabon', dialCode: '241', dialCodeLength: 7},
    { flag: 'GB', name: 'United Kingdom', dialCode: '44', dialCodeLength: 10},
    { flag: 'GD', name: 'Grenada', dialCode: '1-473', dialCodeLength: 10},
    { flag: 'GE', name: 'Georgia', dialCode: '995', dialCodeLength: 9},
    { flag: 'GF', name: 'French Guiana', dialCode: '594', dialCodeLength: 9},
    { flag: 'GG', name: 'Guernsey', dialCode: '44', dialCodeLength: 10},
    { flag: 'GH', name: 'Ghana', dialCode: '233', dialCodeLength: 9},
    { flag: 'GI', name: 'Gibraltar', dialCode: '350', dialCodeLength: 8},
    { flag: 'GL', name: 'Greenland', dialCode: '299', dialCodeLength: 6},
    { flag: 'GM', name: 'Gambia', dialCode: '220', dialCodeLength: 7},
    { flag: 'GN', name: 'Guinea', dialCode: '224', dialCodeLength: 9},
    { flag: 'GP', name: 'Guadeloupe', dialCode: '590', dialCodeLength: 9},
    { flag: 'GQ', name: 'Equatorial Guinea', dialCode: '240', dialCodeLength: 9},
    { flag: 'GR', name: 'Greece', dialCode: '30', dialCodeLength: 10},
    { flag: 'GS', name: 'South Georgia and the South Sandwich Islands', dialCode: '500', dialCodeLength: 5},	
    { flag: 'GT', name: 'Guatemala', dialCode: '502', dialCodeLength: 8},
    { flag: 'GU', name: 'Guam', dialCode: '1-671', dialCodeLength: 10},
    { flag: 'GW', name: 'Guinea-Bissau', dialCode: '245', dialCodeLength: 9},
    { flag: 'GY', name: 'Guyana', dialCode: '592', dialCodeLength: 7},
    { flag: 'HK', name: 'Hong Kong', dialCode: '852', dialCodeLength: 8},
    { flag: 'HM', name: 'Heard Island and McDonald Islands', dialCode: '672',dialCodeLength: 10 },		
    { flag: 'HN', name: 'Honduras', dialCode: '504', dialCodeLength: 8},
    { flag: 'HR', name: 'Croatia', dialCode: '385', dialCodeLength: 9},
    { flag: 'HT', name: 'Haiti', dialCode: '509', dialCodeLength: 8},
    { flag: 'HU', name: 'Hungary', dialCode: '36', dialCodeLength: 9},
    { flag: 'ID', name: 'Indonesia', dialCode: '62', dialCodeLength: 11},
    { flag: 'IE', name: 'Ireland', dialCode: '353', dialCodeLength: 9},
    { flag: 'IL', name: 'Israel', dialCode: '972', dialCodeLength: 9},
    { flag: 'IM', name: 'Isle of Man', dialCode: '44', dialCodeLength: 10},
    { flag: 'IN', name: 'India', dialCode: '91', dialCodeLength: 10},
    { flag: 'IO', name: 'British Indian Ocean Territory', dialCode: '246', dialCodeLength: 7},
    { flag: 'IQ', name: 'Iraq', dialCode: '964', dialCodeLength: 10},	
    { flag: 'IR', name: 'Iran, Islamic Republic of', dialCode: '98', dialCodeLength: 11},
    { flag: 'IS', name: 'Iceland', dialCode: '354', dialCodeLength: 7},
    { flag: 'IT', name: 'Italy', dialCode: '39', dialCodeLength: 10},
    { flag: 'JE', name: 'Jersey', dialCode: '44', dialCodeLength: 10},
    { flag: 'JM', name: 'Jamaica', dialCode: '1-876', dialCodeLength: 10},
    { flag: 'JO', name: 'Jordan', dialCode: '962', dialCodeLength: [8,9]},	
    { flag: 'JP', name: 'Japan', dialCode: '81', suggested: true },
    { flag: 'KE', name: 'Kenya', dialCode: '254', dialCodeLength: 10},
    { flag: 'KG', name: 'Kyrgyzstan', dialCode: '996', dialCodeLength: 9},
    { flag: 'KH', name: 'Cambodia', dialCode: '855', dialCodeLength: 9},
    { flag: 'KI', name: 'Kiribati', dialCode: '686', dialCodeLength: 8},
    { flag: 'KM', name: 'Comoros', dialCode: '269', dialCodeLength: 7},
    { flag: 'KN', name: 'Saint Kitts and Nevis', dialCode: '1-869', dialCodeLength: 10},
    { flag: 'KP', name: "Korea, Democratic People's Republic of", dialCode: '850', dialCodeLength: [4,6,7,13]},	
    { flag: 'KR', name: 'Korea, Republic of', dialCode: '82', dialCodeLength: [7,8]},	
    { flag: 'KW', name: 'Kuwait', dialCode: '965', dialCodeLength: 8},
    { flag: 'KY', name: 'Cayman Islands', dialCode: '1-345', dialCodeLength: 7},
    { flag: 'KZ', name: 'Kazakhstan', dialCode: '7', dialCodeLength: 10},
    { flag: 'LA', name: "Lao People's Democratic Republic", dialCode: '856', dialCodeLength: [8,9]},
    { flag: 'LB', name: 'Lebanon', dialCode: '961', dialCodeLength: [7,8]},	
    { flag: 'LC', name: 'Saint Lucia', dialCode: '1-758', dialCodeLength: 7},
    { flag: 'LI', name: 'Liechtenstein', dialCode: '423', dialCodeLength: 7},
    { flag: 'LK', name: 'Sri Lanka', dialCode: '94', dialCodeLength: 7},
    { flag: 'LR', name: 'Liberia', dialCode: '231', dialCodeLength: [8,9]},	
    { flag: 'LS', name: 'Lesotho', dialCode: '266', dialCodeLength: 8},
    { flag: 'LT', name: 'Lithuania', dialCode: '370', dialCodeLength: 8},
    { flag: 'LU', name: 'Luxembourg', dialCode: '352', dialCodeLength: 9},
    { flag: 'LV', name: 'Latvia', dialCode: '371', dialCodeLength: 8},
    { flag: 'LY', name: 'Libya', dialCode: '218', dialCodeLength: 10},
    { flag: 'MA', name: 'Morocco', dialCode: '212', dialCodeLength: 9},
    { flag: 'MC', name: 'Monaco', dialCode: '377', dialCodeLength: 8},
    { flag: 'MD', name: 'Moldova, Republic of', dialCode: '373', dialCodeLength: 8},
    { flag: 'ME', name: 'Montenegro', dialCode: '382', dialCodeLength: 8},
    { flag: 'MF', name: 'Saint Martin (French part)', dialCode: '590', dialCodeLength: 6},
    { flag: 'MG', name: 'Madagascar', dialCode: '261', dialCodeLength: 7},
    { flag: 'MH', name: 'Marshall Islands', dialCode: '692', dialCodeLength: 7},
    { flag: 'MK', name: 'Macedonia, the Former Yugoslav Republic of', dialCode: '389', dialCodeLength: 8},
    { flag: 'ML', name: 'Mali', dialCode: '223', dialCodeLength: 8},
    { flag: 'MM', name: 'Myanmar', dialCode: '95', min: 7, max: 10},					
    { flag: 'MN', name: 'Mongolia', dialCode: '976', dialCodeLength: 8},
    { flag: 'MO', name: 'Macao', dialCode: '853', dialCodeLength: 8},
    { flag: 'MP', name: 'Northern Mariana Islands', dialCode: '1-670', dialCodeLength: 7},
    { flag: 'MQ', name: 'Martinique', dialCode: '596', dialCodeLength: 9},
    { flag: 'MR', name: 'Mauritania', dialCode: '222', dialCodeLength: 8},
    { flag: 'MS', name: 'Montserrat', dialCode: '1-664', dialCodeLength: 10},
    { flag: 'MT', name: 'Malta', dialCode: '356', dialCodeLength: 8},
    { flag: 'MU', name: 'Mauritius', dialCode: '230', dialCodeLength: 8},
    { flag: 'MV', name: 'Maldives', dialCode: '960', dialCodeLength: 7},
    { flag: 'MW', name: 'Malawi', dialCode: '265', dialCodeLength: [7,8,9]},	
    { flag: 'MX', name: 'Mexico', dialCode: '52', dialCodeLength: 10},
    { flag: 'MY', name: 'Malaysia', dialCode: '60', dialCodeLength: 7},
    { flag: 'MZ', name: 'Mozambique', dialCode: '258', dialCodeLength: 12},
    { flag: 'NA', name: 'Namibia', dialCode: '264', dialCodeLength: 7},
    { flag: 'NC', name: 'New Caledonia', dialCode: '687', dialCodeLength: 6},
    { flag: 'NE', name: 'Niger', dialCode: '227', dialCodeLength: 8},
    { flag: 'NF', name: 'Norfolk Island', dialCode: '672', dialCodeLength: 6},
    { flag: 'NG', name: 'Nigeria', dialCode: '234', dialCodeLength: 8},
    { flag: 'NI', name: 'Nicaragua', dialCode: '505', dialCodeLength: 8},
    { flag: 'NL', name: 'Netherlands', dialCode: '31', dialCodeLength: 9},
    { flag: 'NO', name: 'Norway', dialCode: '47', dialCodeLength: 8},
    { flag: 'NP', name: 'Nepal', dialCode: '977', dialCodeLength: 10},
    { flag: 'NR', name: 'Nauru', dialCode: '674', dialCodeLength: 7},
    { flag: 'NU', name: 'Niue', dialCode: '683', dialCodeLength: 4},
    { flag: 'NZ', name: 'New Zealand', dialCode: '64', dialCodeLength: [8,9]},	
    { flag: 'OM', name: 'Oman', dialCode: '968', dialCodeLength: 8},
    { flag: 'PA', name: 'Panama', dialCode: '507', dialCodeLength: 8},
    { flag: 'PE', name: 'Peru', dialCode: '51', dialCodeLength: 9},
    { flag: 'PF', name: 'French Polynesia', dialCode: '689', dialCodeLength: 8},
    { flag: 'PG', name: 'Papua New Guinea', dialCode: '675', dialCodeLength: 8},	
    { flag: 'PH', name: 'Philippines', dialCode: '63', dialCodeLength: 10},
    { flag: 'PK', name: 'Pakistan', dialCode: '92', dialCodeLength: 10},
    { flag: 'PL', name: 'Poland', dialCode: '48', dialCodeLength: 9},
    { flag: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '508', dialCodeLength: 6},
    { flag: 'PN', name: 'Pitcairn', dialCode: '870', dialCodeLength: 9},	
    { flag: 'PR', name: 'Puerto Rico', dialCode: '1', dialCodeLength: 10},
    { flag: 'PS', name: 'Palestine, State of', dialCode: '970', dialCodeLength: 9},					
    { flag: 'PT', name: 'Portugal', dialCode: '351', dialCodeLength: 9},
    { flag: 'PW', name: 'Palau', dialCode: '680', dialCodeLength: 7},
    { flag: 'PY', name: 'Paraguay', dialCode: '595', dialCodeLength: 9},
    { flag: 'QA', name: 'Qatar', dialCode: '974', dialCodeLength: 8},
    { flag: 'RE', name: 'Reunion', dialCode: '262', dialCodeLength: 10},
    { flag: 'RO', name: 'Romania', dialCode: '40', dialCodeLength: 10},
    { flag: 'RS', name: 'Serbia', dialCode: '381', dialCodeLength: 9},
    { flag: 'RU', name: 'Russian Federation', dialCode: '7', dialCodeLength: 10},
    { flag: 'RW', name: 'Rwanda', dialCode: '250', dialCodeLength: 9},
    { flag: 'SA', name: 'Saudi Arabia', dialCode: '966', dialCodeLength: 9},
    { flag: 'SB', name: 'Solomon Islands', dialCode: '677', dialCodeLength: 7},
    { flag: 'SC', name: 'Seychelles', dialCode: '248', dialCodeLength: 7},
    { flag: 'SD', name: 'Sudan', dialCode: '249', dialCodeLength: 7},
    { flag: 'SE', name: 'Sweden', dialCode: '46', dialCodeLength: 7},
    { flag: 'SG', name: 'Singapore', dialCode: '65', dialCodeLength: 8},
    { flag: 'SH', name: 'Saint Helena', dialCode: '290', dialCodeLength: 4},
    { flag: 'SI', name: 'Slovenia', dialCode: '386', dialCodeLength: 9},
    { flag: 'SJ', name: 'Svalbard and Jan Mayen', dialCode: '47', dialCodeLength: 8},	
    { flag: 'SK', name: 'Slovakia', dialCode: '421', dialCodeLength: 9},
    { flag: 'SL', name: 'Sierra Leone', dialCode: '232', dialCodeLength: 8},
    { flag: 'SM', name: 'San Marino', dialCode: '378', dialCodeLength: 10},	
    { flag: 'SN', name: 'Senegal', dialCode: '221', dialCodeLength: 9},
    { flag: 'SO', name: 'Somalia', dialCode: '252', dialCodeLength: [8,9]},	
    { flag: 'SR', name: 'Suriname', dialCode: '597', dialCodeLength: [6,7]},	
    { flag: 'SS', name: 'South Sudan', dialCode: '211', dialCodeLength: 7},
    { flag: 'ST', name: 'Sao Tome and Principe', dialCode: '239', dialCodeLength: 7},
    { flag: 'SV', name: 'El Salvador', dialCode: '503', dialCodeLength: 8},
    { flag: 'SX', name: 'Sint Maarten (Dutch part)', dialCode: '1-721', dialCodeLength: 10},
    { flag: 'SY', name: 'Syrian Arab Republic', dialCode: '963', dialCodeLength: 7},					
    { flag: 'SZ', name: 'Swaziland', dialCode: '268', dialCodeLength: 8},	
    { flag: 'TC', name: 'Turks and Caicos Islands', dialCode: '1-649', dialCodeLength: 10},
    { flag: 'TD', name: 'Chad', dialCode: '235', dialCodeLength: 6},
    { flag: 'TF', name: 'French Southern Territories', dialCode: '262', dialCodeLength: 10},
    { flag: 'TG', name: 'Togo', dialCode: '228', dialCodeLength: 8},
    { flag: 'TH', name: 'Thailand', dialCode: '66', dialCodeLength: 9},
    { flag: 'TJ', name: 'Tajikistan', dialCode: '992', dialCodeLength: 9},	
    { flag: 'TK', name: 'Tokelau', dialCode: '690', dialCodeLength: 5},
    { flag: 'TL', name: 'Timor-Leste', dialCode: '670', dialCodeLength: 7},
    { flag: 'TM', name: 'Turkmenistan', dialCode: '993', dialCodeLength: 8},	
    { flag: 'TN', name: 'Tunisia', dialCode: '216', dialCodeLength: 8},
    { flag: 'TO', name: 'Tonga', dialCode: '676', dialCodeLength: 5},
    { flag: 'TR', name: 'Turkey', dialCode: '90', dialCodeLength: 11},
    { flag: 'TT', name: 'Trinidad and Tobago', dialCode: '1-868', dialCodeLength: 7},
    { flag: 'TV', name: 'Tuvalu', dialCode: '688', dialCodeLength: 5},
    { flag: 'TW', name: 'Taiwan, Province of China', dialCode: '886', dialCodeLength: 9},	
    { flag: 'TZ', name: 'United Republic of Tanzania', dialCode: '255', dialCodeLength: 7},
    { flag: 'UA', name: 'Ukraine', dialCode: '380', dialCodeLength: 9},
    { flag: 'UG', name: 'Uganda', dialCode: '256', dialCodeLength: 7},
    { flag: 'US', name: 'United States', dialCode: '1', suggested: true, dialCodeLength: 10},
    { flag: 'UY', name: 'Uruguay', dialCode: '598', dialCodeLength: 8},
    { flag: 'UZ', name: 'Uzbekistan', dialCode: '998', dialCodeLength: 9},
    { flag: 'VA', name: 'Holy See (Vatican City State)', dialCode: '379' ,dialCodeLength: 10},			
    { flag: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '1-784', dialCodeLength: 7},
    { flag: 'VE', name: 'Venezuela', dialCode: '58', dialCodeLength: 7},
    { flag: 'VG', name: 'British Virgin Islands', dialCode: '1-284', dialCodeLength: 7},
    { flag: 'VI', name: 'US Virgin Islands', dialCode: '1-340', dialCodeLength: 10},
    { flag: 'VN', name: 'Vietnam', dialCode: '84', dialCodeLength: 9},
    { flag: 'VU', name: 'Vanuatu', dialCode: '678', dialCodeLength: 5},
    { flag: 'WF', name: 'Wallis and Futuna', dialCode: '681', dialCodeLength: 6},
    { flag: 'WS', name: 'Samoa', dialCode: '685', dialCodeLength: [5,6,7]},	 
    { flag: 'XK', name: 'Kosovo', dialCode: '383', dialCodeLength: 8},	
    { flag: 'YE', name: 'Yemen', dialCode: '967', dialCodeLength: 9},
    { flag: 'YT', name: 'Mayotte', dialCode: '262', dialCodeLength: 9},
    { flag: 'ZA', name: 'South Africa', dialCode: '27', dialCodeLength: 9},
    { flag: 'ZM', name: 'Zambia', dialCode: '260', dialCodeLength: 9},
    { flag: 'ZW', name: 'Zimbabwe', dialCode: '263', dialCodeLength: 9},
  ];
}